export const mapCategoriesToOptions = {
  mobile: [
    "ram_storage",
    "rom_storage",
    "operating_system",
    "rear_camera",
    "front_camera",
    "screen_size",
    "cpu",
  ],
  laptop: [
    "ram_storage",
    "rom_storage",
    "operating_system",
    "screen_size",
    "cpu",
  ],
  watch: [
    "diameter",
    "is_digital",
    "is_calling_available",
    "have_fitness_tracker",
  ],
  monitor: ["screen_size"],
  keyboard: [],
  mouse: ["is_wireless"],
  headphone: ["is_wireless"],
  electronics: [],
  painting: [
    "painter_name",
    "time_of_creation",
    "medium",
    "height",
    "width",
    "are_you_painter",
    "want_first_buyer",
  ],
  common: [
    "brand_name",
    "model_name",
    "product_color",
    "set_price",
    "original_price",
    "title",
    "desc",
    "usage_time",
    "bid_start_time",
    "product_appeal",
    "bid_time",
  ],
};

export const mapCategoriesToInput = {
  brand_name: "text",
  model_name: "text",
  ram_storage: "text",
  rom_storage: "text",
  operating_system: "text",
  rear_camera: "text",
  front_camera: "text",
  product_color: "text",
  screen_size: "text",
  cpu: "text",
  set_price: "number",
  original_price: "number",
  title: "text",
  desc: "text",
  usage_time: "date",
  bid_start_time: "time",
  product_appeal: "text",
  bid_time: "number",
  diameter: "number",
  is_digital: "text",
  is_calling_available: "number",
  have_fitness_tracker: "number",
  is_wireless: "text",
  painter_name: "text",
  time_of_creation: "time",
  medium: "text",
  height: "number",
  width: "number",
  are_you_painter: "text",
  want_first_buyer: "text",
};

export const attributesToComponent = {
  brand_name: "Brand",
  model_name: "Model",
  ram_storage: "RAM",
  rom_storage: "ROM",
  operating_system: "Operating System",
  rear_camera: "Rear Camera",
  front_camera: "Front Camera",
  product_color: "Color",
  screen_size: "Screen Size",
  product_set_price: "Starting Price",
  original_price: "Original Price",
  desc: "Description",
  usage_time: "Usage Time",
  bid_time: "Bid Time",
  bid_start_time: "Bid Start Time",
  product_appeal: "Special",
  highest_bid: "Highest Bid",
  cpu: "CPU",
};

export const mapUserFieldsInput = {
  user_name: "text",
  user_email: "text",
  user_first_name: "text",
  user_last_name: "text",
  user_contact_no: "number",
  user_address_line_1: "text",
  user_city: "text",
  user_country: "text",
  user_image: "file",
};

export const mapUserFieldDisplayNames = {
  user_name: "User Name",
  user_email: "Email",
  user_first_name: "First Name",
  user_last_name: "Last Name",
  user_contact_no: "Contact No.",
  user_address_line_1: "Address",
  user_city: "City",
  user_country: "Country",
};

export const mapProductCategory = [
  "all",
  "mobile",
  "laptop",
  "monitor",
  "keyboard",
  "mouse",
  "headphone",
  "electronics",
  "painting",
  "gold",
  "sivler",
  "platinum",
  "diamond",
  "others",
];

export const mapCategoriesToComponent = {
  mobile: {
    brand_name: "Brand",
    model_name: "Model",
    ram_storage: "RAM",
    rom_storage: "Storage",
    operating_system: "Operating System",
    rear_camera: "Rear Camera",
    front_camera: "Front Camera",
    product_color: "Color",
    screen_size: "Screen",
    usage_time: "Usage History",
    product_appeal: "Appeal",
    cpu: "CPU",
  },
  laptop: {
    brand_name: "Brand",
    model_name: "Model",
    ram_storage: "RAM",
    rom_storage: "Storage",
    operating_system: "Operating System",
    front_camera: "Front Camera",
    product_color: "Color",
    screen_size: "Screen",
    usage_time: "Usage History",
    product_appeal: "Appeal",
    cpu: "CPU",
  },
  monitor: {
    brand_name: "Brand",
    model_name: "Model",
    product_color: "Color",
    screen_size: "Screen",
    usage_time: "Usage History",
    product_appeal: "Appeal",
  },
  keyboard: {
    brand_name: "Brand",
    model_name: "Model",
    product_color: "Color",
    usage_time: "Usage History",
    product_appeal: "Appeal",
  },
  mouse: {
    brand_name: "Brand",
    model_name: "Model",
    product_color: "Color",
    usage_time: "Usage History",
    product_appeal: "Appeal",
    is_wireless: "Wireless",
  },
  headphones: {
    brand_name: "Brand",
    model_name: "Model",
    product_color: "Color",
    usage_time: "Usage History",
    product_appeal: "Appeal",
    is_wireless: "Wireless",
  },
  "general-electronics": {
    brand_name: "Brand",
    model_name: "Model",
    product_color: "Color",
    usage_time: "Usage History",
    product_appeal: "Appeal",
  },
  watch: {
    brand_name: "Brand",
    model_name: "Model",
    product_color: "Color",
    usage_time: "Usage History",
    product_appeal: "Appeal",
    diameter: "Diameter",
    is_digital: "Digital",
    is_calling_available: "Calling",
    have_fitness_tracker: "Fitness Tracker",
  },
  painting: {
    painter_name: "Painter Name",
    time_of_creation: "Year of creation",
    medium: "Medium",
    height: "Height",
    width: "Width",
    are_you_painter: "Are you Painter",
    want_first_buyer: "Want first buyer",
  },
};